
const labs=[
{tAr:'عرض التاريخ الحالي',tEn:'Display Current Date',whyAr:'تستخدم SYSDATE لمعرفة تاريخ ووقت قاعدة البيانات. في Oracle نستخدم DUAL لعرض ناتج دالة أو عملية حسابية بدون جدول حقيقي.',whyEn:'SYSDATE returns the database date and time. In Oracle, DUAL is used to display a function or calculation without a real table.',code:'SELECT SYSDATE\nFROM DUAL;',out:[['SYSDATE'],['06-JUL-26']],tipAr:'DUAL جدول خاص شائع في Oracle لتجربة الدوال.',tipEn:'DUAL is a special Oracle table commonly used to test functions.'},
{tAr:'دوال تحويل الحروف',tEn:'Case Conversion Functions',whyAr:'LOWER يحول النص إلى أحرف صغيرة، UPPER إلى أحرف كبيرة، و INITCAP يجعل بداية كل كلمة كبيرة. مفيدة في البحث بدون التأثر بحالة الحروف.',whyEn:'LOWER converts text to lowercase, UPPER to uppercase, and INITCAP capitalizes each word. Useful for case-insensitive searches.',code:"SELECT employee_id, last_name, department_id\nFROM employees\nWHERE LOWER(last_name) = 'higgins';",out:[['EMPLOYEE_ID','LAST_NAME','DEPARTMENT_ID'],['205','Higgins','110']],tipAr:'بدون LOWER قد لا يظهر الموظف إذا كتبت الاسم بحروف مختلفة.',tipEn:'Without LOWER, the employee may not appear if the typed case does not match.'},
{tAr:'دوال التعامل مع النص',tEn:'Character Manipulation Functions',whyAr:'تستخدم CONCAT للدمج، LENGTH لحساب طول النص، INSTR للبحث عن موقع حرف، و SUBSTR لاستخراج جزء من النص.',whyEn:'Use CONCAT to join strings, LENGTH to count characters, INSTR to find a character position, and SUBSTR to extract part of a string.',code:"SELECT employee_id, CONCAT(first_name, last_name) AS name,\n       job_id, LENGTH(last_name), INSTR(last_name, 'a')\nFROM employees\nWHERE SUBSTR(job_id, 4) = 'REP';",out:[['EMPLOYEE_ID','NAME','JOB_ID','LENGTH','INSTR'],['150','PeterTucker','SA_REP','6','0'],['151','DavidBernstein','SA_REP','9','0']],tipAr:'SUBSTR(job_id, 4) يبدأ من الحرف الرابع في job_id.',tipEn:'SUBSTR(job_id, 4) starts from the fourth character of job_id.'},
{tAr:'تداخل الدوال',tEn:'Nesting Functions',whyAr:'يمكن وضع دالة داخل دالة أخرى. التنفيذ يبدأ من أعمق دالة ثم ينتقل للخارج.',whyEn:'A function can be placed inside another function. Evaluation starts from the deepest function and moves outward.',code:"SELECT last_name,\n       UPPER(CONCAT(SUBSTR(last_name, 1, 8), '_US')) AS code\nFROM employees\nWHERE department_id = 60;",out:[['LAST_NAME','CODE'],['Hunold','HUNOLD_US'],['Ernst','ERNST_US']],tipAr:'اقرأ التداخل من الداخل للخارج: SUBSTR ثم CONCAT ثم UPPER.',tipEn:'Read nesting from inside out: SUBSTR, then CONCAT, then UPPER.'},
{tAr:'الدوال الرقمية',tEn:'Numeric Functions',whyAr:'ROUND تقرب الرقم، TRUNC تقص الرقم بدون تقريب، و MOD تعطي باقي القسمة.',whyEn:'ROUND rounds a number, TRUNC cuts it without rounding, and MOD returns the remainder.',code:'SELECT ROUND(45.923,2), TRUNC(45.923,2), MOD(1600,300)\nFROM DUAL;',out:[['ROUND','TRUNC','MOD'],['45.92','45.92','100']],tipAr:'انتبه: TRUNC لا يقرّب، فقط يحذف الأرقام الزائدة.',tipEn:'Remember: TRUNC does not round; it only removes extra digits.'},
{tAr:'الحسابات على التواريخ',tEn:'Date Arithmetic',whyAr:'في Oracle يمكنك طرح تاريخين لمعرفة عدد الأيام، أو إضافة رقم إلى التاريخ لإضافة أيام.',whyEn:'In Oracle, subtracting two dates returns days. Adding a number to a date adds days.',code:'SELECT last_name, (SYSDATE - hire_date) / 7 AS weeks\nFROM employees\nWHERE department_id = 90;',out:[['LAST_NAME','WEEKS'],['King','1100.5'],['Kochhar','987.2']],tipAr:'القسمة على 7 تحول الأيام إلى أسابيع.',tipEn:'Dividing by 7 converts days into weeks.'}
];
function table(rows){return `<table class="table">${rows.map((r,i)=>`<tr>${r.map(c=>i?`<td>${c}</td>`:`<th>${c}</th>`).join('')}</tr>`).join('')}</table>`}
function renderLab(i=0){const lang=localStorage.getItem('lang')||'ar',l=labs[i];document.getElementById('labContent').innerHTML=`<h2>${lang==='ar'?l.tAr:l.tEn}</h2><p class="note">${lang==='ar'?l.whyAr:l.whyEn}</p><div class="codebox"><button class="chip copy-btn" onclick="copyText(\`${l.code.replaceAll('`','\\`')}\`)">${lang==='ar'?'نسخ':'Copy'}</button><pre><code>${l.code}</code></pre></div><h3>${lang==='ar'?'الناتج المتوقع':'Expected Output'}</h3>${table(l.out)}<p class="note">💡 ${lang==='ar'?l.tipAr:l.tipEn}</p>`;location.hash='lab-'+i}
function renderMenu(){const lang=localStorage.getItem('lang')||'ar';document.getElementById('labMenu').innerHTML=labs.map((l,i)=>`<button class="btn ghost" onclick="renderLab(${i})">${i+1}. ${lang==='ar'?l.tAr:l.tEn}</button>`).join('')}renderMenu();let idx=Number((location.hash.match(/lab-(\d+)/)||[])[1]||0);renderLab(idx);document.getElementById('langToggle')?.addEventListener('click',()=>setTimeout(()=>{renderMenu();renderLab(idx)},0));
