
const labs=[
{t:'عرض التاريخ الحالي',why:'تستخدم SYSDATE لمعرفة تاريخ ووقت قاعدة البيانات. في Oracle نستخدم DUAL لعرض ناتج دالة أو عملية حسابية بدون جدول حقيقي.',code:'SELECT SYSDATE\nFROM DUAL;',out:[['SYSDATE'],['06-JUL-26']],tip:'DUAL جدول خاص شائع في Oracle لتجربة الدوال.'},
{t:'دوال تحويل الحروف',why:'LOWER يحول النص إلى أحرف صغيرة، UPPER إلى أحرف كبيرة، و INITCAP يجعل بداية كل كلمة كبيرة. مفيدة في البحث بدون التأثر بحالة الحروف.',code:"SELECT employee_id, last_name, department_id\nFROM employees\nWHERE LOWER(last_name) = 'higgins';",out:[['EMPLOYEE_ID','LAST_NAME','DEPARTMENT_ID'],['205','Higgins','110']],tip:'بدون LOWER قد لا يظهر الموظف إذا كتبت الاسم بحروف مختلفة.'},
{t:'دوال التعامل مع النص',why:'تستخدم CONCAT للدمج، LENGTH لحساب طول النص، INSTR للبحث عن موقع حرف، و SUBSTR لاستخراج جزء من النص.',code:"SELECT employee_id, CONCAT(first_name, last_name) AS name,\n       job_id, LENGTH(last_name), INSTR(last_name, 'a')\nFROM employees\nWHERE SUBSTR(job_id, 4) = 'REP';",out:[['EMPLOYEE_ID','NAME','JOB_ID','LENGTH','INSTR'],['150','PeterTucker','SA_REP','6','0'],['151','DavidBernstein','SA_REP','9','0']],tip:'SUBSTR(job_id, 4) يبدأ من الحرف الرابع في job_id.'},
{t:'تداخل الدوال',why:'يمكن وضع دالة داخل دالة أخرى. التنفيذ يبدأ من أعمق دالة ثم ينتقل للخارج.',code:"SELECT last_name,\n       UPPER(CONCAT(SUBSTR(last_name, 1, 8), '_US')) AS code\nFROM employees\nWHERE department_id = 60;",out:[['LAST_NAME','CODE'],['Hunold','HUNOLD_US'],['Ernst','ERNST_US']],tip:'اقرأ التداخل من الداخل للخارج: SUBSTR ثم CONCAT ثم UPPER.'},
{t:'الدوال الرقمية',why:'ROUND تقرب الرقم، TRUNC تقص الرقم بدون تقريب، و MOD تعطي باقي القسمة.',code:'SELECT ROUND(45.923,2), TRUNC(45.923,2), MOD(1600,300)\nFROM DUAL;',out:[['ROUND','TRUNC','MOD'],['45.92','45.92','100']],tip:'انتبه: TRUNC لا يقرّب، فقط يحذف الأرقام الزائدة.'},
{t:'الحسابات على التواريخ',why:'في Oracle يمكنك طرح تاريخين لمعرفة عدد الأيام، أو إضافة رقم إلى التاريخ لإضافة أيام.',code:'SELECT last_name, (SYSDATE - hire_date) / 7 AS weeks\nFROM employees\nWHERE department_id = 90;',out:[['LAST_NAME','WEEKS'],['King','1100.5'],['Kochhar','987.2']],tip:'القسمة على 7 تحول الأيام إلى أسابيع.'}
];
function table(rows){return `<table class="table">${rows.map((r,i)=>`<tr>${r.map(c=>i?`<td>${c}</td>`:`<th>${c}</th>`).join('')}</tr>`).join('')}</table>`}
function renderLab(i=0){const l=labs[i];document.getElementById('labContent').innerHTML=`<h2>${l.t}</h2><p class="note">${l.why}</p><div class="codebox"><button class="chip copy-btn" onclick="copyText(\`${l.code.replaceAll('`','\\`')}\`)">نسخ</button><pre><code>${l.code}</code></pre></div><h3>الناتج المتوقع</h3>${table(l.out)}<p class="note">💡 ${l.tip}</p>`;location.hash='lab-'+i}
function renderMenu(){document.getElementById('labMenu').innerHTML=labs.map((l,i)=>`<button class="btn ghost" onclick="renderLab(${i})">${i+1}. ${l.t}</button>`).join('')}
renderMenu();let idx=Number((location.hash.match(/lab-(\d+)/)||[])[1]||0);renderLab(idx);
